# Generated by Django 2.1.15 on 2020-04-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(choices=[('AG', 'Agree'), ('DAG', 'Disagree')], default='AG', max_length=2)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_a', models.CharField(max_length=500)),
                ('issue_b', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='votes.Vote'),
        ),
    ]
