# Generated by Django 2.1.15 on 2020-04-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue')], default='red', max_length=2),
        ),
    ]
