# Generated by Django 2.1.15 on 2020-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20200427_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue')], default='red', max_length=4),
        ),
    ]
